//
//  CouponScanModels.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CouponScan {
    // MARK: Use cases
    
    enum ScanPhoto {
        struct Request {
        }
        
        struct Response {
            let name: String?
            let brand: String?
            let barcode: String?
            let expiredDate: String?
        }
        
        struct ViewModel {
            let name: String?
            let brand: String?
            let barcode: String?
            let expiredDate: String?
        }
    }
    
    enum RegisterCoupon {
        struct Request {
            let name: String
            let brand: String
            let barcode: String
            let expiredDate: String
            let image: UIImage
        }
        
        struct Alert {
            let title: String?
            let message: String
        }
    }
}
