//
//  CouponScanViewController.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponScanDisplayLogic: class {
    func displayScanResult(viewModel: CouponScan.PhotoScan.ViewModel)
}

class CouponScanViewController: UIViewController, CouponScanDisplayLogic {
    var interactor: CouponScanBusinessLogic?
    var router: (NSObjectProtocol & CouponScanRoutingLogic & CouponScanDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CouponScanInteractor()
        let presenter = CouponScanPresenter()
        let router = CouponScanRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        scanImageOCR()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func scanImageOCR() {
        let request = CouponScan.PhotoScan.Request()
        interactor?.scanPhoto(request: request)
    }
    
    func displayScanResult(viewModel: CouponScan.PhotoScan.ViewModel) {
        DispatchQueue.main.async {
            self.nameInput.text = viewModel.name
            self.brandInput.text = viewModel.brand
            self.barcodeInput.text = viewModel.barcode
            self.expiredInput.text = viewModel.expiredDate
        }
    }
    
    // MARK: View
    
    let header: CouponScanHeader = {
        let header = CouponScanHeader()
        return header
    }()
    
    let imageView: UIImageView = {
        let imageView = UIImageView()
        imageView.layer.cornerRadius = 10
        imageView.clipsToBounds = true
        imageView.backgroundColor = .systemBackground
        imageView.contentMode = .scaleAspectFit
        return imageView
    }()
    
    let nameLabel: UILabel = {
        let label = UILabel()
        label.text = "이름"
        label.font = UIFont.systemFont(ofSize: 14, weight: .semibold)
        return label
    }()
    
    let nameInput: InputFieldView = {
        let input = InputFieldView(placeHolder: "이름 입력하세요")
        return input
    }()
    
    let brandLabel: UILabel = {
        let label = UILabel()
        label.text = "브랜드"
        label.font = UIFont.systemFont(ofSize: 14, weight: .semibold)

        return label
    }()
    
    let brandInput: InputFieldView = {
        let input = InputFieldView(placeHolder: "브랜드를 입력하세요")
        return input
    }()
    
    let expiredLabel: UILabel = {
        let label = UILabel()
        label.font = UIFont.systemFont(ofSize: 14, weight: .semibold)
        label.text = "유효기간"
        return label
    }()
    
    let expiredInput: InputFieldView = {
        let input = InputFieldView(placeHolder: "유효기간을 입력하세요")
        return input
    }()
    
    let barcodeLabel: UILabel = {
        let label = UILabel()
        label.font = UIFont.systemFont(ofSize: 14, weight: .semibold)
        label.text = "바코드"
        return label
    }()
    
    let barcodeInput: InputFieldView = {
        let input = InputFieldView(placeHolder: "바코드를 입력하세요")
        return input
    }()
    
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
}

extension CouponScanViewController {
    
    @objc func touchedBackIcon() {
        self.navigationController?.popViewController(animated: true)
    }
    
    @objc func touchedCompleteIcon() {
        self.dismiss(animated: true, completion: nil)

    }
    
    func setupUI() {
        guard let image = router?.dataStore?.image else { return }
        let ratio = image.size.height / image.size.width
        nameInput.delegate = self
        brandInput.delegate = self
        header.backIcon.addTarget(self, action: #selector(touchedBackIcon), for: .touchUpInside)
        header.completeIcon.addTarget(self, action: #selector(touchedCompleteIcon), for: .touchUpInside)

        self.view.backgroundColor = .systemBackground
        imageView.image = image
        
        [imageView, nameLabel, nameInput, brandLabel, brandInput, header, expiredLabel, expiredInput, barcodeLabel, barcodeInput].forEach {
            view.addSubview($0)
        }
        
        nameLabel.snp.makeConstraints { make in
            make.top.equalTo(imageView.snp.bottom).offset(20)
            make.leading.equalToSuperview().offset(10)
        }
        
        nameInput.snp.makeConstraints { make in
            make.top.equalTo(nameLabel.snp.bottom)
            make.leading.equalToSuperview().offset(10)
            make.trailing.equalToSuperview().offset(-10)
        }
        
        brandLabel.snp.makeConstraints { make in
            make.top.equalTo(nameInput.snp.bottom).offset(30)
            make.leading.equalToSuperview().offset(10)
        }
        
        brandInput.snp.makeConstraints { make in
            make.top.equalTo(brandLabel.snp.bottom)
            make.leading.equalToSuperview().offset(10)
            make.trailing.equalToSuperview().offset(-10)
        }
        
        expiredLabel.snp.makeConstraints { make in
            make.top.equalTo(brandInput.snp.bottom).offset(30)
            make.leading.equalToSuperview().offset(10)
        }
        
        expiredInput.snp.makeConstraints { make in
            make.top.equalTo(expiredLabel.snp.bottom)
            make.leading.equalToSuperview().offset(10)
            make.trailing.equalToSuperview().offset(-10)
        }
        
        barcodeLabel.snp.makeConstraints { make in
            make.top.equalTo(expiredInput.snp.bottom).offset(30)
            make.leading.equalToSuperview().offset(10)
        }
        
        barcodeInput.snp.makeConstraints { make in
            make.top.equalTo(barcodeLabel.snp.bottom)
            make.leading.equalToSuperview().offset(10)
            make.trailing.equalToSuperview().offset(-10)
        }
        
        imageView.snp.makeConstraints { make in
            make.top.equalTo(header.snp.bottom).offset(10)
            make.centerX.equalToSuperview()
            make.width.equalToSuperview().multipliedBy(0.5)
            make.height.equalTo(imageView.snp.width).multipliedBy(min(ratio, 1.6))
        }
        print(ratio)
        header.snp.makeConstraints { make in
            make.top.equalTo(view.safeAreaLayoutGuide)
            make.height.equalTo(43)
            make.leading.trailing.equalToSuperview()
        }
        
    }
}

extension CouponScanViewController: UITextFieldDelegate {
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        if textField == nameInput {
            print("nameinput touched")
        }
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        self.view.endEditing(true)
    }
}
