//
//  CouponScanPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponScanPresentationLogic {
    func presentSomething(response: CouponScan.Something.Response)
}

class CouponScanPresenter: CouponScanPresentationLogic {
    weak var viewController: CouponScanDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CouponScan.Something.Response) {
        let viewModel = CouponScan.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
