//
//  CouponScanWorker.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CouponScanState {
    case success
    case dateFormatError
    case inputValueError
}

class CouponScanWorker {
    func isVaildCoupon(request: CouponScan.RegisterCoupon.Request) -> CouponScanState {
        guard request.name != "",
              request.brand != "",
              request.barcode != "",
              let date = request.expiredDate
        else {
            return .inputValueError }
        guard let _ = date.toDate(format: "yyyy.MM.dd") else {
            return .dateFormatError
        }
        return .success
    }
}
