//
//  CouponScanInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponScanBusinessLogic {
    func doSomething(request: CouponScan.Something.Request)
}

protocol CouponScanDataStore {
    var image: UIImage? { get set }
}

class CouponScanInteractor: CouponScanBusinessLogic, CouponScanDataStore {
    var presenter: CouponScanPresentationLogic?
    var worker: CouponScanWorker?
    var image: UIImage?
    
    // MARK: Do something
    
    func doSomething(request: CouponScan.Something.Request) {
        worker = CouponScanWorker()
        worker?.doSomeWork()
        
        let response = CouponScan.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
