//
//  CouponScanWorker.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CouponScanError: Error {
    case inputValueIsNil
}

class CouponScanWorker {
    func isVaildCoupon(request: CouponScan.RegisterCoupon.Request) -> (Bool, String) {
        guard let _ = request.name,
              let _ = request.brand,
              let date = request.expiredDate,
              let _ = request.barcode else {
            //alert
            return (false, "inputValueisNil") }
        
        let df = DateFormatter()
        df.dateFormat = "yyyy.MM.dd"
        print(df.date(from: date))
        print(date)
        return (true, "")
    }
}
