//
//  CouponScanPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponScanPresentationLogic {
    func presentScanResult(response: CouponScan.ScanPhoto.Response)
}

class CouponScanPresenter: CouponScanPresentationLogic {
    weak var viewController: CouponScanDisplayLogic?
    
    // MARK: Do something
    
    func presentScanResult(response: CouponScan.ScanPhoto.Response) {
        let viewModel = CouponScan.ScanPhoto.ViewModel(name: response.name, brand: response.brand, barcode: response.barcode, expiredDate: response.expiredDate)
        viewController?.displayScanResult(viewModel: viewModel)
    }
}
