//
//  CouponScanModels.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/09.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CouponScan {
    // MARK: Use cases
    
    enum PhotoScan {
        struct Request {
        }
        
        struct Response {
            let boxes: [CGRect]
        }
        
        struct ViewModel {
            let boxes: [CGRect]
        }
    }
}
