//
//  CouponListPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponListPresentationLogic {
    func presentCoupons(response: CouponList.FetchCoupon.Response)
}

class CouponListPresenter: CouponListPresentationLogic {
    weak var viewController: CouponListDisplayLogic?
    
    let manager = ImageManager()

    // MARK: Do something
    
    func presentCoupons(response: CouponList.FetchCoupon.Response) {
        let displayed = response.coupons.map { c -> ViewModelCoupon in
            return ViewModelCoupon(coupon: c)
        }
        var filtered = applyFilter(coupons: displayed)
        let names = filtered.count > 1 ? ["사용전", "사용완료"] : ["사용전"]
        if filtered.count == 0 {
            filtered = [.empty]
        }
        let viewModel = CouponList.FetchCoupon.ViewModel(sectionName: names, coupons: filtered)
        viewController?.displayCouponList(viewModel: viewModel)
    }
    
    func applyFilter(coupons: [ViewModelCoupon]) ->
    [ViewModelCoupon] {
        let order = UserDefaults.standard.integer(forKey: FilterOption.order.rawValue)
        let isShowExpired = UserDefaults.standard.integer(forKey: FilterOption.expired.rawValue)
        var unusedCoupon = coupons.filter { !$0.isUsed }
        if isShowExpired == 1 {
            unusedCoupon = unusedCoupon.filter { $0.remainDay >= 0 }
        }
        if order == 1 {
            unusedCoupon = unusedCoupon.sorted { $0.remainDay < $1.remainDay }
        }
        return unusedCoupon
    }
}
