//
//  CouponListRouter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CouponListRoutingLogic {
    func routeToCouponAdd()
    func routeToCouponDetail()
}

protocol CouponListDataPassing {
    var dataStore: CouponListDataStore? { get }
}

class CouponListRouter: NSObject, CouponListRoutingLogic, CouponListDataPassing {
    weak var viewController: CouponListViewController?
    var dataStore: CouponListDataStore?
    
    // MARK: Routing
    
    func routeToCouponAdd() {
        let controller = CouponAddViewController()
        let navController = UINavigationController()
        navController.viewControllers = [controller]
        navController.navigationBar.isHidden = true
        navController.modalPresentationStyle = .fullScreen
        controller.modalPresentationStyle = .fullScreen
        viewController?.present(navController, animated: true, completion: nil)
    }
    
    func routeToCouponDetail() {
        let controller = CouponDetailViewController()
        viewController?.present(controller, animated: true, completion: nil)
    }
}
