//
//  CouponListInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponListBusinessLogic {
    func fetchCoupons(request: CouponList.FetchCoupon.Request)
}

protocol CouponListDataStore {

}

class CouponListInteractor: CouponListBusinessLogic, CouponListDataStore {
    var presenter: CouponListPresentationLogic?
    var worker: CouponListWorker?

    // MARK: fetch Coupons
    
    func fetchCoupons(request: CouponList.FetchCoupon.Request) {
        let coupons: [Coupon] = CoreDataManager.shared.fetchAllCoupons()
        let response = CouponList.FetchCoupon.Response(coupons: coupons)
        presenter?.presentCoupons(response: response)
    }
}
