//
//  CouponListModels.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CouponList {
    // MARK: Use cases
    struct DisplayedCoupon {
        let name: String
        let brand: String
        let expiredDate: Date
        let dateString: String
        let remainDay: Int
        let remainDayString: String
        let image: UIImage?
        let tagColor: UIColor
    }
    
    enum FetchCoupon {
        struct Request {
        }
        
        struct Response {
            let coupons: [Coupon]
        }
        
        struct ViewModel {

            let coupons: [DisplayedCoupon]
        }
    }
}
