//
//  CouponListPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponListPresentationLogic {
    func presentSomething(response: CouponList.Something.Response)
}

class CouponListPresenter: CouponListPresentationLogic {
    weak var viewController: CouponListDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CouponList.Something.Response) {
        let viewModel = CouponList.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
