//
//  CouponListInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021  . All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponListBusinessLogic {
    func doSomething(request: CouponList.Something.Request)
}

protocol CouponListDataStore {
    //var name: String { get set }
}

class CouponListInteractor: CouponListBusinessLogic, CouponListDataStore {
    var presenter: CouponListPresentationLogic?
    var worker: CouponListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CouponList.Something.Request) {
        worker = CouponListWorker()
        worker?.doSomeWork()
        
        let response = CouponList.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
