//
//  CouponAddInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Photos

protocol CouponAddBusinessLogic {
    func fetchPhotos(request: CouponAdd.fetchPhoto.Request)
    func changeSelectedImage(request: CouponAdd.fetchOnePhoto.Request)
}

protocol CouponAddDataStore {
    var selectedImage: UIImage? { get set }
}

class CouponAddInteractor: CouponAddBusinessLogic, CouponAddDataStore {
    var presenter: CouponAddPresentationLogic?
    var worker: CouponAddWorker?
    var selectedImage: UIImage?

    // MARK: fetchPhotos
    
    func fetchPhotos(request: CouponAdd.fetchPhoto.Request) {
        let assets = PhotoAssetLoader().loadAssets()
        let response = CouponAdd.fetchPhoto.Response(assets: assets)
        self.presenter?.presentFetchedPhoto(response: response)
    }

    func changeSelectedImage(request: CouponAdd.fetchOnePhoto.Request) {
        ImageLoader.shared.loadImageHighQuality(request.asset) { image in
            guard let img = try? image.get() else { return }
            self.selectedImage = img
            let response = CouponAdd.fetchOnePhoto.ImageResponse(image: img)
            self.presenter?.presentFetchOnePhoto(response: response)
        }
        let cellResponse = CouponAdd.fetchOnePhoto.CellResponse(prev: request.prev, curr: request.curr)
        self.presenter?.presentSelectedCell(response: cellResponse)
    }
}
