//
//  CouponAddPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponAddPresentationLogic {
    func presentFetchedPhoto(response: CouponAdd.fetchPhoto.Response)
    func presentFetchOnePhoto(response: CouponAdd.fetchOnePhoto.Response)

}

class CouponAddPresenter: CouponAddPresentationLogic {
    weak var viewController: CouponAddDisplayLogic?
    
    // MARK: Do something
    
    func presentFetchedPhoto(response: CouponAdd.fetchPhoto.Response) {
        let viewModel = CouponAdd.fetchPhoto.ViewModel(images: response.images)
        viewController?.displayFetchedPhotos(viewModel: viewModel)
    }
    
    func presentFetchOnePhoto(response: CouponAdd.fetchOnePhoto.Response) {
        let viewModel = CouponAdd.fetchOnePhoto.ViewModel(image: response.image)
        viewController?.displayLargeImageView(viewModel: viewModel)
    }
}
