//
//  CouponAddModels.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/08.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Photos

enum CouponAdd {
    
    // MARK: fetchPhoto
    
    enum fetchPhoto {
        struct Request {
        }
        
        struct Response {
            let assets: [PHAsset]
        }
        
        struct ViewModel {
            let assets: [PHAsset]
        }
    }
    
    enum fetchOnePhoto {
        struct Request {
            let prev: IndexPath
            let curr: IndexPath
            let asset: PHAsset
        }
        
        struct ImageResponse {
            let image: UIImage
        }
        
        struct CellResponse {
            let prev: IndexPath
            let curr: IndexPath
        }
        
        struct ImageViewModel {
            let image: UIImage
        }
        
        struct CellViewModel {
            let prev: IndexPath
            let curr: IndexPath
        }
    }
}
