//
//  FilterInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/22.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterBusinessLogic {
    func doSomething(request: Filter.Something.Request)
}

protocol FilterDataStore {
    //var name: String { get set }
}

class FilterInteractor: FilterBusinessLogic, FilterDataStore {
    var presenter: FilterPresentationLogic?
    var worker: FilterWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Filter.Something.Request) {
        worker = FilterWorker()
        worker?.doSomeWork()
        
        let response = Filter.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
