//
//  CouponDetailPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/21.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CouponDetailPresentationLogic {
    func presentSomething(response: CouponDetail.Something.Response)
}

class CouponDetailPresenter: CouponDetailPresentationLogic {
    weak var viewController: CouponDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: CouponDetail.Something.Response) {
        let viewModel = CouponDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
