//
//  SearchPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/26.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic {
    func presentSomething(response: Search.Something.Response)
}

class SearchPresenter: SearchPresentationLogic {
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Search.Something.Response) {
        let viewModel = Search.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
