//
//  SearchResultPresenter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/27.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultPresentationLogic {
    func presentSearchedCoupon(response: SearchResult.SearchCoupon.Response)
}

class SearchResultPresenter: SearchResultPresentationLogic {
    weak var viewController: SearchResultDisplayLogic?
    
    // MARK: Do something
    
    func presentSearchedCoupon(response: SearchResult.SearchCoupon.Response) {
        let viewModel = SearchResult.SearchCoupon.ViewModel(coupons: response.coupons)
        viewController?.displaySearchedCoupon(viewModel: viewModel)
    }
}
