//
//  SearchResultRouter.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/27.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchResultRoutingLogic {
    func routeToCouponDetail(image: UIImage?, barcode: String, id: UUID)
}

protocol SearchResultDataPassing {
    var dataStore: SearchResultDataStore? { get }
}

class SearchResultRouter: NSObject, SearchResultRoutingLogic, SearchResultDataPassing {
    weak var viewController: SearchResultViewController?
    var dataStore: SearchResultDataStore?
    
    // MARK: Routing
    
    func routeToCouponDetail(image: UIImage?, barcode: String, id: UUID) {
        let controller = CouponDetailViewController()
        guard
            var destDataStore = controller.router?.dataStore else { return }
        destDataStore.barcode = barcode
        destDataStore.identifier = id
        controller.image = image
        viewController?.present(controller, animated: true, completion: nil)
    }
}
