//
//  SearchResultInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/27.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultBusinessLogic {
    func fetchSearchCoupon(request: SearchResult.SearchCoupon.Request)
}

protocol SearchResultDataStore {
    var keyword: String { get set }
}

class SearchResultInteractor: SearchResultBusinessLogic, SearchResultDataStore {
    var presenter: SearchResultPresentationLogic?
    var worker: SearchResultWorker?
    var keyword: String = ""

    // MARK: Do something
    
    func fetchSearchCoupon(request: SearchResult.SearchCoupon.Request) {
        worker = SearchResultWorker()
        worker?.doSomeWork()
        
        let response = SearchResult.SearchCoupon.Response()
        presenter?.presentSearchedCoupon(response: response)
    }
}
