//
//  SearchResultInteractor.swift
//  ticonMoa
//
//  Created by 채훈기 on 2021/07/27.
//  Copyright (c) 2021 hoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchResultBusinessLogic {
    func fetchSearchCoupon(request: SearchResult.SearchCoupon.Request)
}

protocol SearchResultDataStore {
    var keyword: String { get set }
}

class SearchResultInteractor: SearchResultBusinessLogic, SearchResultDataStore {
    var presenter: SearchResultPresentationLogic?
    var worker: SearchResultWorker?
    var keyword: String = ""

    // MARK: Do something
    
    func fetchSearchCoupon(request: SearchResult.SearchCoupon.Request) {
        var coupons: [Coupon] = CoreDataManager.shared.fetchAllCoupons()
        coupons = coupons.filter { !$0.isUsed &&
            isSearchedCoupon(coupon: $0, keyword: request.keyword)
        }
        let response = SearchResult.SearchCoupon.Response(coupons: coupons)
        presenter?.presentSearchedCoupon(response: response)
    }
    
    func isSearchedCoupon(coupon: Coupon, keyword: String) -> Bool {
        if coupon.name.contains(keyword) || coupon.brand.contains(keyword) {
            return true
        }
        return false
    }
}
